language: python
python:
  - 3.6

os:
  - linux
  - osx

matrix:
  include:
    - os: osx
      language: generic

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install python3
    python -m venv venv
    source venv/bin/activate
    # A manual check that the correct version of Python is running.
    python --version
  fi

install:
- pip install -U pip
- pip install -U -r requirements.txt

script:
- bash ci.bash

notifications:
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
