language: python
matrix:
  include:
  - os: linux
    dist: trusty
    python: 3.6
  - os: osx
    language: generic
before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew upgrade python3
    python3 --version
    python3 -m pip install -U pip
    which pip3
  fi
install:
- pip3 install -U pip setuptools
- pip3 install -U -r requirements.txt
script:
- bash ci.bash
notifications:
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always

deploy:
  provider: releases
  api_key:
    secure: Y2xTZ2bTDFzFdAnD8wrlSi1yT/YCV9mfyJyr6mQO1UqB8AUhTZ1UguTmQWdIM/lFoLRPmo41ptNvpNqMqEGer+BsgqhVsD8DwG4E1y7IhioUJTxtdw3OvxKmG4iCosQEND/Beis+DCGe7uPJ5YCoXuCmVWLJBx3FbGwJ8z05Z5gauk/6589Usii/hReMZ4a1R5ajKd/lZK2USRMr0vBovd/HcxCJhMsF8spc43I8kiLga7ZTFru2n3FkuGeJNpT/+VjTX2WhmiGOA3LAyvdg1o57JS5bvsGHFZ0eRc1n/YnPqa8rDrwD+gV/aELqAB6cFyxrF2fBq1XxhKS5iBQV94q+wUX63mxgxSltpux15k9sPMD8/BMTiCH6akgNbriagVE9iLHVe8QCfBW6yabrTBE5bcMrugOsVbRdslhUd2BHPnosyEDXMjjKKCwLV2/dscCuardQgAyj2ANwFmS7IUgBNOmh9sm2/KPO9cPpb/ULlY6DX6NgnC0uHAV7uk7vEKMWpIf1JKD/hUckPXOPmEneXIW86z1hY0uOnVL8TPPDaY35FhrMHFU/nr2roZsSwRE4kISSb7CJ6m6tMR37rt/c3R2Btqa///4G+EAhI4kjpi0iStPrt9UMPLgCi2zmQrV2VBNuuM/53KEd4ZxmF7HXKAFzzeySehbIStPJVoI=
  file: dist/*
  file_glob: true
  on:
    repo: chaostoolkit/chaostoolkit-bundler
    tags: true
  skip_cleanup: true
  tag_name: $TRAVIS_TAG
  draft: false