language: python

matrix:
  include:
    - os: linux
      dist: trusty
      python: 3.6
    - os: osx
      language: generic

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    # brew update
    brew install gnu-sed --with-default-names
    brew upgrade python3
    python3 --version
    python3 -m pip install -U pip
    which pip3
  fi

install:
- pip3 install -U pip setuptools
- pip3 install -U -r requirements.txt

script:
- bash ci.bash

notifications:
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
