language: python
python:
- 3.6

os:
  - linux
  - osx

install:
- pip install -U -r requirements.txt
- which chaos

script:
- bash ci.bash

notifications:
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
