language: python
python:
  - 3.6

os:
  - linux
  - osx

matrix:
  include:
    - os: osx
      language: generic

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install python3
    python --version
  fi
  python3 -m venv venv
  source venv/bin/activate

install:
- venv/bin/pip install -U -r requirements.txt

script:
- bash ci.bash

notifications:
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
