language: python
matrix:
  include:
  - os: linux
    dist: trusty
    python: 3.6
  - os: osx
    language: generic

env:
  global:
  - GH_USER: chaostoolkit-ci
  - secure: "hNXbarN5CrrEwaaBASUCXULH8YZe0w/2Rc7s7SNNOI/mT2iTvro+/318I1SATbeafXHk5D0+idid62fJ55XFybH9xtiaAtXB1uxNk6Gkp0IeoxhzPZGYhWOnLTsS6ePutgprUVgq1RczdttVgATUOtd4s3gS/6RW19tsocShL5NECBp7sH9Fb+B2bE3/N6TMecSFy8s5U5aehM/8nASf3OtgYxm03W9vHnmJABQmnSF5AjeRzFXYyx2IiPijLL70e25SAE9KWKXdUxwdsus7tpJA+o6sGaXJScG50I5yjP11Jm1+rTI7N6Cea0/pfQaVyQuzxAfZtW8xzkVfbOqTonST03T4/FOO2auTpZuUb5/pMlkCSGLl/bHz8Bkel3MAnQpSbk7jbdppwaIjh19rwcbVjxesQy+HE3aVU2pPVW9Kw2aiYvIge2s5ZGuixwu0guTqkkOBPQYCHwwZrqLsc7GYNelS3z8PmRbWxEhiCIJ5V/oj0V5+4fBtaXk9qn87ISkduACSTltgSFua3jPQ6zZDcqzTcmam2BQlyA6xzGdwG8tYDWHHmdsYI3Vprk/wtprLsxSMhZRmC0yqacnTVL4RTVUrldSP5bzIA+EbXFg0INjvRoJPaYKG6a2hHKrozaHbsAvxFryYgqstEiArxyWAfkagvUNlZoB8f46Gxcs="
  - secure: "LJH1nXZ5+oDAVTR8XEPSjxlkBIe1mGL1AVG/aYwc14SFeOPAPFrz6lDGMwGhbZxzEdWkL6wLAX8g+EDs6+YLQvgc8X6c7R/rDNcJHZn5aeifqQ31f2GrZG9S9gh3VCoYBzYNdDoeuNmZeCa0AcqTH+gCKHi3eBHckqEmZVLjUC5pzvdkNlPwm8Q0YSeHeqzdwEFeZ7WpiDrQsia+K97m9y2u3n4L4FAdDQrHcw+E9Juj3fuWVvzPS1xOXc+Xh1eH5IB75pjWSBTBQQJHI4UQacnjoBAYdF9WXPg19xK17lB7usxyOORTyDwyI7cgOko8U4jddwU+cjz87/xJa21KX0/8E6feLO9NqegW3b5ydI/xAR+STJXXnbBOM4cfHenm/PHjJpFmjGcxMceAr0+pHS42YwTERfr80VkdUsDaZXq3PCVHLJSjeFZ8pnEn8wA5CqeIh5e0xoUECnTd1lpMvF04WI7cxC25JUOJAxzbKdvTyVDVBz28ncDATqHnY6pLYhptr8xDFvQ3T042AX455Oci1WacuM9T7Tzy3vXGSnU1dPMsPuvNvip3eyocVHLI3zsCQDYklzLDllTlerqgMd3WfOntrvauySZvwlpMk4SWM2emZVcUBN65ylJdeirzeGzvAyawChUn42xUmoLzLO8SSRhFOJFr+QbqUHW12Nw="

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew upgrade python3
    python3 --version
    python3 -m pip install -U pip
    which pip3
  fi
install:
- pip3 install -U pip setuptools
- pip3 install -U -r requirements.txt -r requirements-chaostoolkit.txt
script:
- bash ci.bash

branches:
  only:
    - master

notifications:
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always

deploy:
  provider: releases
  api_key:
    secure: Y2xTZ2bTDFzFdAnD8wrlSi1yT/YCV9mfyJyr6mQO1UqB8AUhTZ1UguTmQWdIM/lFoLRPmo41ptNvpNqMqEGer+BsgqhVsD8DwG4E1y7IhioUJTxtdw3OvxKmG4iCosQEND/Beis+DCGe7uPJ5YCoXuCmVWLJBx3FbGwJ8z05Z5gauk/6589Usii/hReMZ4a1R5ajKd/lZK2USRMr0vBovd/HcxCJhMsF8spc43I8kiLga7ZTFru2n3FkuGeJNpT/+VjTX2WhmiGOA3LAyvdg1o57JS5bvsGHFZ0eRc1n/YnPqa8rDrwD+gV/aELqAB6cFyxrF2fBq1XxhKS5iBQV94q+wUX63mxgxSltpux15k9sPMD8/BMTiCH6akgNbriagVE9iLHVe8QCfBW6yabrTBE5bcMrugOsVbRdslhUd2BHPnosyEDXMjjKKCwLV2/dscCuardQgAyj2ANwFmS7IUgBNOmh9sm2/KPO9cPpb/ULlY6DX6NgnC0uHAV7uk7vEKMWpIf1JKD/hUckPXOPmEneXIW86z1hY0uOnVL8TPPDaY35FhrMHFU/nr2roZsSwRE4kISSb7CJ6m6tMR37rt/c3R2Btqa///4G+EAhI4kjpi0iStPrt9UMPLgCi2zmQrV2VBNuuM/53KEd4ZxmF7HXKAFzzeySehbIStPJVoI=
  file: dist/*
  file_glob: true
  on:
    repo: chaostoolkit/chaostoolkit-bundler
    tags: true
  skip_cleanup: true
  tag_name: $TRAVIS_TAG
  draft: false